// build.mjs - assembles assets/js/app.js from assets/js/app/*.js.
// The parts share one closure (opened in 01-state.js, closed in 08-shell.js),
// so they are concatenated in file-name order. GitHub Pages serves the result
// as-is: there is no other build step.
//   node tools/build.mjs          write assets/js/app.js
//   node tools/build.mjs --check  exit 1 if app.js is out of date
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'assets/js/app');
const out = join(root, 'assets/js/app.js');
const parts = readdirSync(dir).filter(f => /^\d\d-.*\.js$/.test(f)).sort();
const banner = '/* GENERATED by tools/build.mjs from assets/js/app/*.js - edit the parts, then run: node tools/build.mjs */\n';
const body = banner + parts.map(f => readFileSync(join(dir, f), 'utf8').replace(/\s+$/, '') + '\n').join('');

if (process.argv.includes('--check')) {
  const cur = existsSync(out) ? readFileSync(out, 'utf8') : '';
  if (cur !== body) { console.error('assets/js/app.js is out of date. Run: node tools/build.mjs'); process.exit(1); }
  console.log('app.js is up to date (' + parts.length + ' parts).');
} else {
  writeFileSync(out, body);
  console.log('Wrote assets/js/app.js from ' + parts.length + ' parts: ' + parts.join(', '));
}
